version: '3'

services:
     strapi:
       build: .
       volumes:
         - .app:/strapi-app
       ports:
         - '1337:1337'
       environment:
         - DATABASE_CLIENT=sqlite
         - DATABASE_FILENAME=./texts.db



     es:
       image: elasticsearch:6.5.0
       ports:
         - "9200:9200"

     app:
       build: .
       tty: true
       ports:
         - "8000:8000"
       restart: on-failure
       command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
       volumes:
         - .:/app
       depends_on:
         - strapi
         - es

       env_file:
         - .env