# Generated by Django 5.0.2 on 2024-09-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_document_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
    ]
